// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: version_resolver.proto

package version_resolver

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	upgrades_registry "blazar/internal/pkg/proto/upgrades_registry"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Version struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// upgrade height the version tag is valid for

	Height int64 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty" gorm:"primaryKey;not null"`
	// chain network name

	Network string `protobuf:"bytes,2,opt,name=network,proto3" json:"network,omitempty" gorm:"primaryKey;type:text;not null"`
	// version tag
	Tag string `protobuf:"bytes,3,opt,name=tag,proto3" json:"tag,omitempty"`
	// source of the upgrade

	Source upgrades_registry.ProviderType `protobuf:"varint,4,opt,name=source,proto3,enum=ProviderType" json:"source,omitempty" gorm:"not null"`
	// the version priority

	Priority int32 `protobuf:"varint,5,opt,name=priority,proto3" json:"priority,omitempty" gorm:"primaryKey;not null"`
	// created_at timestamp

	CreatedAt     uint64 `protobuf:"varint,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty" gorm:"not null"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Version) Reset() {
	*x = Version{}
	mi := &file_version_resolver_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Version) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Version) ProtoMessage() {}

func (x *Version) ProtoReflect() protoreflect.Message {
	mi := &file_version_resolver_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Version.ProtoReflect.Descriptor instead.
func (*Version) Descriptor() ([]byte, []int) {
	return file_version_resolver_proto_rawDescGZIP(), []int{0}
}

func (x *Version) GetHeight() int64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Version) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Version) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *Version) GetSource() upgrades_registry.ProviderType {
	if x != nil {
		return x.Source
	}
	return upgrades_registry.ProviderType(0)
}

func (x *Version) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Version) GetCreatedAt() uint64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type RegisterVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       *Version               `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Overwrite     bool                   `protobuf:"varint,2,opt,name=overwrite,proto3" json:"overwrite,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterVersionRequest) Reset() {
	*x = RegisterVersionRequest{}
	mi := &file_version_resolver_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterVersionRequest) ProtoMessage() {}

func (x *RegisterVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_version_resolver_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterVersionRequest.ProtoReflect.Descriptor instead.
func (*RegisterVersionRequest) Descriptor() ([]byte, []int) {
	return file_version_resolver_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterVersionRequest) GetVersion() *Version {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *RegisterVersionRequest) GetOverwrite() bool {
	if x != nil {
		return x.Overwrite
	}
	return false
}

type RegisterVersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterVersionResponse) Reset() {
	*x = RegisterVersionResponse{}
	mi := &file_version_resolver_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterVersionResponse) ProtoMessage() {}

func (x *RegisterVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_version_resolver_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterVersionResponse.ProtoReflect.Descriptor instead.
func (*RegisterVersionResponse) Descriptor() ([]byte, []int) {
	return file_version_resolver_proto_rawDescGZIP(), []int{2}
}

type GetVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DisableCache  bool                   `protobuf:"varint,1,opt,name=disable_cache,json=disableCache,proto3" json:"disable_cache,omitempty"`
	Height        int64                  `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVersionRequest) Reset() {
	*x = GetVersionRequest{}
	mi := &file_version_resolver_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersionRequest) ProtoMessage() {}

func (x *GetVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_version_resolver_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersionRequest.ProtoReflect.Descriptor instead.
func (*GetVersionRequest) Descriptor() ([]byte, []int) {
	return file_version_resolver_proto_rawDescGZIP(), []int{3}
}

func (x *GetVersionRequest) GetDisableCache() bool {
	if x != nil {
		return x.DisableCache
	}
	return false
}

func (x *GetVersionRequest) GetHeight() int64 {
	if x != nil {
		return x.Height
	}
	return 0
}

type GetVersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       *Version               `protobuf:"bytes,1,opt,name=version,proto3,oneof" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVersionResponse) Reset() {
	*x = GetVersionResponse{}
	mi := &file_version_resolver_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersionResponse) ProtoMessage() {}

func (x *GetVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_version_resolver_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersionResponse.ProtoReflect.Descriptor instead.
func (*GetVersionResponse) Descriptor() ([]byte, []int) {
	return file_version_resolver_proto_rawDescGZIP(), []int{4}
}

func (x *GetVersionResponse) GetVersion() *Version {
	if x != nil {
		return x.Version
	}
	return nil
}

type ListVersionsRequest struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	DisableCache  bool                            `protobuf:"varint,1,opt,name=disable_cache,json=disableCache,proto3" json:"disable_cache,omitempty"`
	Height        *int64                          `protobuf:"varint,2,opt,name=height,proto3,oneof" json:"height,omitempty"`
	Source        *upgrades_registry.ProviderType `protobuf:"varint,3,opt,name=source,proto3,enum=ProviderType,oneof" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVersionsRequest) Reset() {
	*x = ListVersionsRequest{}
	mi := &file_version_resolver_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVersionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVersionsRequest) ProtoMessage() {}

func (x *ListVersionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_version_resolver_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVersionsRequest.ProtoReflect.Descriptor instead.
func (*ListVersionsRequest) Descriptor() ([]byte, []int) {
	return file_version_resolver_proto_rawDescGZIP(), []int{5}
}

func (x *ListVersionsRequest) GetDisableCache() bool {
	if x != nil {
		return x.DisableCache
	}
	return false
}

func (x *ListVersionsRequest) GetHeight() int64 {
	if x != nil && x.Height != nil {
		return *x.Height
	}
	return 0
}

func (x *ListVersionsRequest) GetSource() upgrades_registry.ProviderType {
	if x != nil && x.Source != nil {
		return *x.Source
	}
	return upgrades_registry.ProviderType(0)
}

type ListVersionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Versions      []*Version             `protobuf:"bytes,1,rep,name=versions,proto3" json:"versions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVersionsResponse) Reset() {
	*x = ListVersionsResponse{}
	mi := &file_version_resolver_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVersionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVersionsResponse) ProtoMessage() {}

func (x *ListVersionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_version_resolver_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVersionsResponse.ProtoReflect.Descriptor instead.
func (*ListVersionsResponse) Descriptor() ([]byte, []int) {
	return file_version_resolver_proto_rawDescGZIP(), []int{6}
}

func (x *ListVersionsResponse) GetVersions() []*Version {
	if x != nil {
		return x.Versions
	}
	return nil
}

var File_version_resolver_proto protoreflect.FileDescriptor

const file_version_resolver_proto_rawDesc = "" +
	"\n" +
	"\x16version_resolver.proto\x1a\x17upgrades_registry.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xaf\x01\n" +
	"\aVersion\x12\x16\n" +
	"\x06height\x18\x01 \x01(\x03R\x06height\x12\x18\n" +
	"\anetwork\x18\x02 \x01(\tR\anetwork\x12\x10\n" +
	"\x03tag\x18\x03 \x01(\tR\x03tag\x12%\n" +
	"\x06source\x18\x04 \x01(\x0e2\r.ProviderTypeR\x06source\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\x05R\bpriority\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\x04R\tcreatedAt\"Z\n" +
	"\x16RegisterVersionRequest\x12\"\n" +
	"\aversion\x18\x01 \x01(\v2\b.VersionR\aversion\x12\x1c\n" +
	"\toverwrite\x18\x02 \x01(\bR\toverwrite\"\x19\n" +
	"\x17RegisterVersionResponse\"P\n" +
	"\x11GetVersionRequest\x12#\n" +
	"\rdisable_cache\x18\x01 \x01(\bR\fdisableCache\x12\x16\n" +
	"\x06height\x18\x02 \x01(\x03R\x06height\"I\n" +
	"\x12GetVersionResponse\x12'\n" +
	"\aversion\x18\x01 \x01(\v2\b.VersionH\x00R\aversion\x88\x01\x01B\n" +
	"\n" +
	"\b_version\"\x99\x01\n" +
	"\x13ListVersionsRequest\x12#\n" +
	"\rdisable_cache\x18\x01 \x01(\bR\fdisableCache\x12\x1b\n" +
	"\x06height\x18\x02 \x01(\x03H\x00R\x06height\x88\x01\x01\x12*\n" +
	"\x06source\x18\x03 \x01(\x0e2\r.ProviderTypeH\x01R\x06source\x88\x01\x01B\t\n" +
	"\a_heightB\t\n" +
	"\a_source\"<\n" +
	"\x14ListVersionsResponse\x12$\n" +
	"\bversions\x18\x01 \x03(\v2\b.VersionR\bversions2\x98\x02\n" +
	"\x0fVersionResolver\x12\\\n" +
	"\n" +
	"AddVersion\x12\x17.RegisterVersionRequest\x1a\x18.RegisterVersionResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/v1/versions/add\x12O\n" +
	"\n" +
	"GetVersion\x12\x12.GetVersionRequest\x1a\x13.GetVersionResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/versions/get\x12V\n" +
	"\fListVersions\x12\x14.ListVersionsRequest\x1a\x15.ListVersionsResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/versions/listB%Z#internal/pkg/proto/version_resolverb\x06proto3"

var (
	file_version_resolver_proto_rawDescOnce sync.Once
	file_version_resolver_proto_rawDescData []byte
)

func file_version_resolver_proto_rawDescGZIP() []byte {
	file_version_resolver_proto_rawDescOnce.Do(func() {
		file_version_resolver_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_version_resolver_proto_rawDesc), len(file_version_resolver_proto_rawDesc)))
	})
	return file_version_resolver_proto_rawDescData
}

var file_version_resolver_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_version_resolver_proto_goTypes = []any{
	(*Version)(nil),                     // 0: Version
	(*RegisterVersionRequest)(nil),      // 1: RegisterVersionRequest
	(*RegisterVersionResponse)(nil),     // 2: RegisterVersionResponse
	(*GetVersionRequest)(nil),           // 3: GetVersionRequest
	(*GetVersionResponse)(nil),          // 4: GetVersionResponse
	(*ListVersionsRequest)(nil),         // 5: ListVersionsRequest
	(*ListVersionsResponse)(nil),        // 6: ListVersionsResponse
	(upgrades_registry.ProviderType)(0), // 7: ProviderType
}
var file_version_resolver_proto_depIdxs = []int32{
	7, // 0: Version.source:type_name -> ProviderType
	0, // 1: RegisterVersionRequest.version:type_name -> Version
	0, // 2: GetVersionResponse.version:type_name -> Version
	7, // 3: ListVersionsRequest.source:type_name -> ProviderType
	0, // 4: ListVersionsResponse.versions:type_name -> Version
	1, // 5: VersionResolver.AddVersion:input_type -> RegisterVersionRequest
	3, // 6: VersionResolver.GetVersion:input_type -> GetVersionRequest
	5, // 7: VersionResolver.ListVersions:input_type -> ListVersionsRequest
	2, // 8: VersionResolver.AddVersion:output_type -> RegisterVersionResponse
	4, // 9: VersionResolver.GetVersion:output_type -> GetVersionResponse
	6, // 10: VersionResolver.ListVersions:output_type -> ListVersionsResponse
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_version_resolver_proto_init() }
func file_version_resolver_proto_init() {
	if File_version_resolver_proto != nil {
		return
	}
	file_version_resolver_proto_msgTypes[4].OneofWrappers = []any{}
	file_version_resolver_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_version_resolver_proto_rawDesc), len(file_version_resolver_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_version_resolver_proto_goTypes,
		DependencyIndexes: file_version_resolver_proto_depIdxs,
		MessageInfos:      file_version_resolver_proto_msgTypes,
	}.Build()
	File_version_resolver_proto = out.File
	file_version_resolver_proto_goTypes = nil
	file_version_resolver_proto_depIdxs = nil
}
