// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: upgrades_registry.proto

package upgrades_registry

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpgradeStep int32

const (
	// NONE is the default step of an upgrade. It means that the upgrade is not being executed
	UpgradeStep_NONE UpgradeStep = 0
	// MONITORING means that blazar sees the upcoming upgrade and is monitoring the chain for the upgrade height
	UpgradeStep_MONITORING UpgradeStep = 1
	// DOCKER_COMPOSE_FILE_UPGRADE indicates the blazar is executing the core part of the upgrade vua docker compose
	UpgradeStep_COMPOSE_FILE_UPGRADE UpgradeStep = 2
	// PRE_UPGRADE_CHECK indicates that the blazar is executing the pre-upgrade checks
	UpgradeStep_PRE_UPGRADE_CHECK UpgradeStep = 3
	// POST_UPGRADE_CHECK indicates that the blazar is executing the post-upgrade checks
	UpgradeStep_POST_UPGRADE_CHECK UpgradeStep = 4
)

// Enum value maps for UpgradeStep.
var (
	UpgradeStep_name = map[int32]string{
		0: "NONE",
		1: "MONITORING",
		2: "COMPOSE_FILE_UPGRADE",
		3: "PRE_UPGRADE_CHECK",
		4: "POST_UPGRADE_CHECK",
	}
	UpgradeStep_value = map[string]int32{
		"NONE":                 0,
		"MONITORING":           1,
		"COMPOSE_FILE_UPGRADE": 2,
		"PRE_UPGRADE_CHECK":    3,
		"POST_UPGRADE_CHECK":   4,
	}
)

func (x UpgradeStep) Enum() *UpgradeStep {
	p := new(UpgradeStep)
	*p = x
	return p
}

func (x UpgradeStep) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UpgradeStep) Descriptor() protoreflect.EnumDescriptor {
	return file_upgrades_registry_proto_enumTypes[0].Descriptor()
}

func (UpgradeStep) Type() protoreflect.EnumType {
	return &file_upgrades_registry_proto_enumTypes[0]
}

func (x UpgradeStep) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UpgradeStep.Descriptor instead.
func (UpgradeStep) EnumDescriptor() ([]byte, []int) {
	return file_upgrades_registry_proto_rawDescGZIP(), []int{0}
}

type UpgradeStatus int32

const (
	// UNKNOWN is the default status of an upgrade. It means that the status
	UpgradeStatus_UNKNOWN UpgradeStatus = 0
	// SCHEDULED is the initial status of an upgrade. It means that the
	// upgrade is registered with the registry but it's not active yet.
	//
	// An upgrade coming from the chain governance that is still being voted on, is marked as scheduled
	UpgradeStatus_SCHEDULED UpgradeStatus = 1
	// ACTIVE means that the upgrade is acknowledged by network governance or a user and is ready to be executed.
	UpgradeStatus_ACTIVE UpgradeStatus = 2
	// EXECUTING means that the upgrade is currently being executed. The height is reached.
	UpgradeStatus_EXECUTING UpgradeStatus = 3
	// COMPLETED means that the upgrade has been successfully executed.
	UpgradeStatus_COMPLETED UpgradeStatus = 4
	// FAILED means that the upgrade has failed to execute.
	UpgradeStatus_FAILED UpgradeStatus = 5
	// CANCELLED means that the upgrade has been cancelled by a user or the network
	UpgradeStatus_CANCELLED UpgradeStatus = 6
	// EXPIRED means that the upgrade time has passed and blazar did not do anything about it (e.g historical upgrade from the chain governance)
	UpgradeStatus_EXPIRED UpgradeStatus = 7
)

// Enum value maps for UpgradeStatus.
var (
	UpgradeStatus_name = map[int32]string{
		0: "UNKNOWN",
		1: "SCHEDULED",
		2: "ACTIVE",
		3: "EXECUTING",
		4: "COMPLETED",
		5: "FAILED",
		6: "CANCELLED",
		7: "EXPIRED",
	}
	UpgradeStatus_value = map[string]int32{
		"UNKNOWN":   0,
		"SCHEDULED": 1,
		"ACTIVE":    2,
		"EXECUTING": 3,
		"COMPLETED": 4,
		"FAILED":    5,
		"CANCELLED": 6,
		"EXPIRED":   7,
	}
)

func (x UpgradeStatus) Enum() *UpgradeStatus {
	p := new(UpgradeStatus)
	*p = x
	return p
}

func (x UpgradeStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UpgradeStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_upgrades_registry_proto_enumTypes[1].Descriptor()
}

func (UpgradeStatus) Type() protoreflect.EnumType {
	return &file_upgrades_registry_proto_enumTypes[1]
}

func (x UpgradeStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UpgradeStatus.Descriptor instead.
func (UpgradeStatus) EnumDescriptor() ([]byte, []int) {
	return file_upgrades_registry_proto_rawDescGZIP(), []int{1}
}

type UpgradeType int32

const (
	// GOVERNANCE is a coordinated upgrade that is initiated by the chain
	// governance. The upgrade is expected to be coordinated across all
	// validators at specific height.
	//
	// Requirements:
	// * there is an onchain governance proposal that has passed
	UpgradeType_GOVERNANCE UpgradeType = 0
	// NON_GOVERNANCE_COORDINATED the upgrade is not coming from the chain,
	// but rather is initiated by the operators.
	//
	// Requirements:
	// * there should be no onchain governance proposal
	// * the upgrade is expected to happen at the same height for all validators (usually it's a state breaking change)
	UpgradeType_NON_GOVERNANCE_COORDINATED UpgradeType = 1
	// NON_GOVERNANCE_UNCOORDINATED the upgrade is not coming from the chain,
	// but rather is initiated by the operators.
	//
	// Requirements:
	// * there should be no onchain governance proposal
	// * the upgrade is not expected to happen at any specific height. Validators are free to upgrade at their own pace. (usually non-state breaking changes)
	UpgradeType_NON_GOVERNANCE_UNCOORDINATED UpgradeType = 2
)

// Enum value maps for UpgradeType.
var (
	UpgradeType_name = map[int32]string{
		0: "GOVERNANCE",
		1: "NON_GOVERNANCE_COORDINATED",
		2: "NON_GOVERNANCE_UNCOORDINATED",
	}
	UpgradeType_value = map[string]int32{
		"GOVERNANCE":                   0,
		"NON_GOVERNANCE_COORDINATED":   1,
		"NON_GOVERNANCE_UNCOORDINATED": 2,
	}
)

func (x UpgradeType) Enum() *UpgradeType {
	p := new(UpgradeType)
	*p = x
	return p
}

func (x UpgradeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UpgradeType) Descriptor() protoreflect.EnumDescriptor {
	return file_upgrades_registry_proto_enumTypes[2].Descriptor()
}

func (UpgradeType) Type() protoreflect.EnumType {
	return &file_upgrades_registry_proto_enumTypes[2]
}

func (x UpgradeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UpgradeType.Descriptor instead.
func (UpgradeType) EnumDescriptor() ([]byte, []int) {
	return file_upgrades_registry_proto_rawDescGZIP(), []int{2}
}

type ProviderType int32

const (
	// CHAIN means that the upgrade is coming from onchain governance
	ProviderType_CHAIN ProviderType = 0
	// LOCAL means that the upgrade is coming from blazar local storage
	ProviderType_LOCAL ProviderType = 1
	// DATABASE means that the upgrade is coming from the database (e.g PostgreSQL)
	ProviderType_DATABASE ProviderType = 2
)

// Enum value maps for ProviderType.
var (
	ProviderType_name = map[int32]string{
		0: "CHAIN",
		1: "LOCAL",
		2: "DATABASE",
	}
	ProviderType_value = map[string]int32{
		"CHAIN":    0,
		"LOCAL":    1,
		"DATABASE": 2,
	}
)

func (x ProviderType) Enum() *ProviderType {
	p := new(ProviderType)
	*p = x
	return p
}

func (x ProviderType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProviderType) Descriptor() protoreflect.EnumDescriptor {
	return file_upgrades_registry_proto_enumTypes[3].Descriptor()
}

func (ProviderType) Type() protoreflect.EnumType {
	return &file_upgrades_registry_proto_enumTypes[3]
}

func (x ProviderType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProviderType.Descriptor instead.
func (ProviderType) EnumDescriptor() ([]byte, []int) {
	return file_upgrades_registry_proto_rawDescGZIP(), []int{3}
}

type Upgrade struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// the height at which the upgrade is expected to happen

	Height int64 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty" gorm:"primaryKey;not null"`
	// docker image tag

	Tag string `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty" gorm:"type:text;not null"`
	// cosmos network name (e.g. cosmoshub) or chain id (e.g. cosmoshub-4)

	Network string `protobuf:"bytes,3,opt,name=network,proto3" json:"network,omitempty" gorm:"primaryKey;type:text;not null"`
	// the short title of the upgrade (e.g. "Coordinated upgrade to v0.42.4 announced on discord channel #announcements")

	Name string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty" gorm:"type:text;not null"`
	// type of the upgrade (defines what checks and actions should be taken)

	Type UpgradeType `protobuf:"varint,5,opt,name=type,proto3,enum=UpgradeType" json:"type,omitempty" gorm:"not null"`
	// status of the upgrade (DONT set this field manually, it's managed by the registry)

	Status UpgradeStatus `protobuf:"varint,6,opt,name=status,proto3,enum=UpgradeStatus" json:"status,omitempty" gorm:"default:0;not null"`
	// current execution step (DONT set this field manually, it's managed by the registry)

	Step UpgradeStep `protobuf:"varint,7,opt,name=step,proto3,enum=UpgradeStep" json:"step,omitempty" gorm:"default:0;not null"`
	// priority of the upgrade (highest priority wins)

	Priority int32 `protobuf:"varint,8,opt,name=priority,proto3" json:"priority,omitempty" gorm:"primaryKey;not null"`
	// source of the upgrade

	Source ProviderType `protobuf:"varint,9,opt,name=source,proto3,enum=ProviderType" json:"source,omitempty" gorm:"not null"`
	// propoal id associated with the upgrade
	ProposalId *int64 `protobuf:"varint,10,opt,name=proposal_id,json=proposalId,proto3,oneof" json:"proposal_id,omitempty"`
	// created_at timestamp

	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty" gorm:"not null;serializer:timestamppb"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Upgrade) Reset() {
	*x = Upgrade{}
	mi := &file_upgrades_registry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Upgrade) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Upgrade) ProtoMessage() {}

func (x *Upgrade) ProtoReflect() protoreflect.Message {
	mi := &file_upgrades_registry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Upgrade.ProtoReflect.Descriptor instead.
func (*Upgrade) Descriptor() ([]byte, []int) {
	return file_upgrades_registry_proto_rawDescGZIP(), []int{0}
}

func (x *Upgrade) GetHeight() int64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Upgrade) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *Upgrade) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Upgrade) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Upgrade) GetType() UpgradeType {
	if x != nil {
		return x.Type
	}
	return UpgradeType_GOVERNANCE
}

func (x *Upgrade) GetStatus() UpgradeStatus {
	if x != nil {
		return x.Status
	}
	return UpgradeStatus_UNKNOWN
}

func (x *Upgrade) GetStep() UpgradeStep {
	if x != nil {
		return x.Step
	}
	return UpgradeStep_NONE
}

func (x *Upgrade) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Upgrade) GetSource() ProviderType {
	if x != nil {
		return x.Source
	}
	return ProviderType_CHAIN
}

func (x *Upgrade) GetProposalId() int64 {
	if x != nil && x.ProposalId != nil {
		return *x.ProposalId
	}
	return 0
}

func (x *Upgrade) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// This is the structure of <chain-home>/blazar/upgrades.json
type Upgrades struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Upgrades      []*Upgrade             `protobuf:"bytes,1,rep,name=upgrades,proto3" json:"upgrades,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Upgrades) Reset() {
	*x = Upgrades{}
	mi := &file_upgrades_registry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Upgrades) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Upgrades) ProtoMessage() {}

func (x *Upgrades) ProtoReflect() protoreflect.Message {
	mi := &file_upgrades_registry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Upgrades.ProtoReflect.Descriptor instead.
func (*Upgrades) Descriptor() ([]byte, []int) {
	return file_upgrades_registry_proto_rawDescGZIP(), []int{1}
}

func (x *Upgrades) GetUpgrades() []*Upgrade {
	if x != nil {
		return x.Upgrades
	}
	return nil
}

type AddUpgradeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The new upgrade to be registered
	Upgrade *Upgrade `protobuf:"bytes,1,opt,name=upgrade,proto3" json:"upgrade,omitempty"`
	// If set to true, the upgrade will be overwritten if it already exists
	Overwrite     bool `protobuf:"varint,2,opt,name=overwrite,proto3" json:"overwrite,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddUpgradeRequest) Reset() {
	*x = AddUpgradeRequest{}
	mi := &file_upgrades_registry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddUpgradeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUpgradeRequest) ProtoMessage() {}

func (x *AddUpgradeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_upgrades_registry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUpgradeRequest.ProtoReflect.Descriptor instead.
func (*AddUpgradeRequest) Descriptor() ([]byte, []int) {
	return file_upgrades_registry_proto_rawDescGZIP(), []int{2}
}

func (x *AddUpgradeRequest) GetUpgrade() *Upgrade {
	if x != nil {
		return x.Upgrade
	}
	return nil
}

func (x *AddUpgradeRequest) GetOverwrite() bool {
	if x != nil {
		return x.Overwrite
	}
	return false
}

type AddUpgradeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddUpgradeResponse) Reset() {
	*x = AddUpgradeResponse{}
	mi := &file_upgrades_registry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddUpgradeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUpgradeResponse) ProtoMessage() {}

func (x *AddUpgradeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_upgrades_registry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUpgradeResponse.ProtoReflect.Descriptor instead.
func (*AddUpgradeResponse) Descriptor() ([]byte, []int) {
	return file_upgrades_registry_proto_rawDescGZIP(), []int{3}
}

type ListUpgradesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DisableCache  bool                   `protobuf:"varint,1,opt,name=disable_cache,json=disableCache,proto3" json:"disable_cache,omitempty"`
	Height        *int64                 `protobuf:"varint,2,opt,name=height,proto3,oneof" json:"height,omitempty"`
	Type          *UpgradeType           `protobuf:"varint,3,opt,name=type,proto3,enum=UpgradeType,oneof" json:"type,omitempty"`
	Source        *ProviderType          `protobuf:"varint,4,opt,name=source,proto3,enum=ProviderType,oneof" json:"source,omitempty"`
	Status        []UpgradeStatus        `protobuf:"varint,5,rep,packed,name=status,proto3,enum=UpgradeStatus" json:"status,omitempty"`
	Limit         *int64                 `protobuf:"varint,6,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUpgradesRequest) Reset() {
	*x = ListUpgradesRequest{}
	mi := &file_upgrades_registry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUpgradesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUpgradesRequest) ProtoMessage() {}

func (x *ListUpgradesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_upgrades_registry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUpgradesRequest.ProtoReflect.Descriptor instead.
func (*ListUpgradesRequest) Descriptor() ([]byte, []int) {
	return file_upgrades_registry_proto_rawDescGZIP(), []int{4}
}

func (x *ListUpgradesRequest) GetDisableCache() bool {
	if x != nil {
		return x.DisableCache
	}
	return false
}

func (x *ListUpgradesRequest) GetHeight() int64 {
	if x != nil && x.Height != nil {
		return *x.Height
	}
	return 0
}

func (x *ListUpgradesRequest) GetType() UpgradeType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return UpgradeType_GOVERNANCE
}

func (x *ListUpgradesRequest) GetSource() ProviderType {
	if x != nil && x.Source != nil {
		return *x.Source
	}
	return ProviderType_CHAIN
}

func (x *ListUpgradesRequest) GetStatus() []UpgradeStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *ListUpgradesRequest) GetLimit() int64 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

type ListUpgradesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Upgrades      []*Upgrade             `protobuf:"bytes,1,rep,name=upgrades,proto3" json:"upgrades,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUpgradesResponse) Reset() {
	*x = ListUpgradesResponse{}
	mi := &file_upgrades_registry_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUpgradesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUpgradesResponse) ProtoMessage() {}

func (x *ListUpgradesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_upgrades_registry_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUpgradesResponse.ProtoReflect.Descriptor instead.
func (*ListUpgradesResponse) Descriptor() ([]byte, []int) {
	return file_upgrades_registry_proto_rawDescGZIP(), []int{5}
}

func (x *ListUpgradesResponse) GetUpgrades() []*Upgrade {
	if x != nil {
		return x.Upgrades
	}
	return nil
}

type CancelUpgradeRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Height int64                  `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Source ProviderType           `protobuf:"varint,2,opt,name=source,proto3,enum=ProviderType" json:"source,omitempty"`
	// if set to true, the upgrade is cancelled through the state machine, in this case 'source' is ignored
	Force         bool `protobuf:"varint,3,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelUpgradeRequest) Reset() {
	*x = CancelUpgradeRequest{}
	mi := &file_upgrades_registry_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelUpgradeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelUpgradeRequest) ProtoMessage() {}

func (x *CancelUpgradeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_upgrades_registry_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelUpgradeRequest.ProtoReflect.Descriptor instead.
func (*CancelUpgradeRequest) Descriptor() ([]byte, []int) {
	return file_upgrades_registry_proto_rawDescGZIP(), []int{6}
}

func (x *CancelUpgradeRequest) GetHeight() int64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *CancelUpgradeRequest) GetSource() ProviderType {
	if x != nil {
		return x.Source
	}
	return ProviderType_CHAIN
}

func (x *CancelUpgradeRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type CancelUpgradeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelUpgradeResponse) Reset() {
	*x = CancelUpgradeResponse{}
	mi := &file_upgrades_registry_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelUpgradeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelUpgradeResponse) ProtoMessage() {}

func (x *CancelUpgradeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_upgrades_registry_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelUpgradeResponse.ProtoReflect.Descriptor instead.
func (*CancelUpgradeResponse) Descriptor() ([]byte, []int) {
	return file_upgrades_registry_proto_rawDescGZIP(), []int{7}
}

// ForceSyncRequest is used to force the registry to sync the upgrades from all registered providers
type ForceSyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForceSyncRequest) Reset() {
	*x = ForceSyncRequest{}
	mi := &file_upgrades_registry_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForceSyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForceSyncRequest) ProtoMessage() {}

func (x *ForceSyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_upgrades_registry_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForceSyncRequest.ProtoReflect.Descriptor instead.
func (*ForceSyncRequest) Descriptor() ([]byte, []int) {
	return file_upgrades_registry_proto_rawDescGZIP(), []int{8}
}

type ForceSyncResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// the height at which the registry is currently synced
	Height        int64 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForceSyncResponse) Reset() {
	*x = ForceSyncResponse{}
	mi := &file_upgrades_registry_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForceSyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForceSyncResponse) ProtoMessage() {}

func (x *ForceSyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_upgrades_registry_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForceSyncResponse.ProtoReflect.Descriptor instead.
func (*ForceSyncResponse) Descriptor() ([]byte, []int) {
	return file_upgrades_registry_proto_rawDescGZIP(), []int{9}
}

func (x *ForceSyncResponse) GetHeight() int64 {
	if x != nil {
		return x.Height
	}
	return 0
}

var File_upgrades_registry_proto protoreflect.FileDescriptor

const file_upgrades_registry_proto_rawDesc = "" +
	"\n" +
	"\x17upgrades_registry.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x81\x03\n" +
	"\aUpgrade\x12\x16\n" +
	"\x06height\x18\x01 \x01(\x03R\x06height\x12\x10\n" +
	"\x03tag\x18\x02 \x01(\tR\x03tag\x12\x18\n" +
	"\anetwork\x18\x03 \x01(\tR\anetwork\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12 \n" +
	"\x04type\x18\x05 \x01(\x0e2\f.UpgradeTypeR\x04type\x12&\n" +
	"\x06status\x18\x06 \x01(\x0e2\x0e.UpgradeStatusR\x06status\x12 \n" +
	"\x04step\x18\a \x01(\x0e2\f.UpgradeStepR\x04step\x12\x1a\n" +
	"\bpriority\x18\b \x01(\x05R\bpriority\x12%\n" +
	"\x06source\x18\t \x01(\x0e2\r.ProviderTypeR\x06source\x12$\n" +
	"\vproposal_id\x18\n" +
	" \x01(\x03H\x00R\n" +
	"proposalId\x88\x01\x01\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAtB\x0e\n" +
	"\f_proposal_id\"0\n" +
	"\bUpgrades\x12$\n" +
	"\bupgrades\x18\x01 \x03(\v2\b.UpgradeR\bupgrades\"U\n" +
	"\x11AddUpgradeRequest\x12\"\n" +
	"\aupgrade\x18\x01 \x01(\v2\b.UpgradeR\aupgrade\x12\x1c\n" +
	"\toverwrite\x18\x02 \x01(\bR\toverwrite\"\x14\n" +
	"\x12AddUpgradeResponse\"\x96\x02\n" +
	"\x13ListUpgradesRequest\x12#\n" +
	"\rdisable_cache\x18\x01 \x01(\bR\fdisableCache\x12\x1b\n" +
	"\x06height\x18\x02 \x01(\x03H\x00R\x06height\x88\x01\x01\x12%\n" +
	"\x04type\x18\x03 \x01(\x0e2\f.UpgradeTypeH\x01R\x04type\x88\x01\x01\x12*\n" +
	"\x06source\x18\x04 \x01(\x0e2\r.ProviderTypeH\x02R\x06source\x88\x01\x01\x12&\n" +
	"\x06status\x18\x05 \x03(\x0e2\x0e.UpgradeStatusR\x06status\x12\x19\n" +
	"\x05limit\x18\x06 \x01(\x03H\x03R\x05limit\x88\x01\x01B\t\n" +
	"\a_heightB\a\n" +
	"\x05_typeB\t\n" +
	"\a_sourceB\b\n" +
	"\x06_limit\"<\n" +
	"\x14ListUpgradesResponse\x12$\n" +
	"\bupgrades\x18\x01 \x03(\v2\b.UpgradeR\bupgrades\"k\n" +
	"\x14CancelUpgradeRequest\x12\x16\n" +
	"\x06height\x18\x01 \x01(\x03R\x06height\x12%\n" +
	"\x06source\x18\x02 \x01(\x0e2\r.ProviderTypeR\x06source\x12\x14\n" +
	"\x05force\x18\x03 \x01(\bR\x05force\"\x17\n" +
	"\x15CancelUpgradeResponse\"\x12\n" +
	"\x10ForceSyncRequest\"+\n" +
	"\x11ForceSyncResponse\x12\x16\n" +
	"\x06height\x18\x01 \x01(\x03R\x06height*p\n" +
	"\vUpgradeStep\x12\b\n" +
	"\x04NONE\x10\x00\x12\x0e\n" +
	"\n" +
	"MONITORING\x10\x01\x12\x18\n" +
	"\x14COMPOSE_FILE_UPGRADE\x10\x02\x12\x15\n" +
	"\x11PRE_UPGRADE_CHECK\x10\x03\x12\x16\n" +
	"\x12POST_UPGRADE_CHECK\x10\x04*}\n" +
	"\rUpgradeStatus\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\r\n" +
	"\tSCHEDULED\x10\x01\x12\n" +
	"\n" +
	"\x06ACTIVE\x10\x02\x12\r\n" +
	"\tEXECUTING\x10\x03\x12\r\n" +
	"\tCOMPLETED\x10\x04\x12\n" +
	"\n" +
	"\x06FAILED\x10\x05\x12\r\n" +
	"\tCANCELLED\x10\x06\x12\v\n" +
	"\aEXPIRED\x10\a*_\n" +
	"\vUpgradeType\x12\x0e\n" +
	"\n" +
	"GOVERNANCE\x10\x00\x12\x1e\n" +
	"\x1aNON_GOVERNANCE_COORDINATED\x10\x01\x12 \n" +
	"\x1cNON_GOVERNANCE_UNCOORDINATED\x10\x02*2\n" +
	"\fProviderType\x12\t\n" +
	"\x05CHAIN\x10\x00\x12\t\n" +
	"\x05LOCAL\x10\x01\x12\f\n" +
	"\bDATABASE\x10\x022\xf5\x02\n" +
	"\x0fUpgradeRegistry\x12R\n" +
	"\n" +
	"AddUpgrade\x12\x12.AddUpgradeRequest\x1a\x13.AddUpgradeResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/v1/upgrades/add\x12V\n" +
	"\fListUpgrades\x12\x14.ListUpgradesRequest\x1a\x15.ListUpgradesResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/upgrades/list\x12^\n" +
	"\rCancelUpgrade\x12\x15.CancelUpgradeRequest\x1a\x16.CancelUpgradeResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/v1/upgrades/cancel\x12V\n" +
	"\tForceSync\x12\x11.ForceSyncRequest\x1a\x12.ForceSyncResponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/v1/upgrades/force_syncB&Z$internal/pkg/proto/upgrades_registryb\x06proto3"

var (
	file_upgrades_registry_proto_rawDescOnce sync.Once
	file_upgrades_registry_proto_rawDescData []byte
)

func file_upgrades_registry_proto_rawDescGZIP() []byte {
	file_upgrades_registry_proto_rawDescOnce.Do(func() {
		file_upgrades_registry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_upgrades_registry_proto_rawDesc), len(file_upgrades_registry_proto_rawDesc)))
	})
	return file_upgrades_registry_proto_rawDescData
}

var file_upgrades_registry_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_upgrades_registry_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_upgrades_registry_proto_goTypes = []any{
	(UpgradeStep)(0),              // 0: UpgradeStep
	(UpgradeStatus)(0),            // 1: UpgradeStatus
	(UpgradeType)(0),              // 2: UpgradeType
	(ProviderType)(0),             // 3: ProviderType
	(*Upgrade)(nil),               // 4: Upgrade
	(*Upgrades)(nil),              // 5: Upgrades
	(*AddUpgradeRequest)(nil),     // 6: AddUpgradeRequest
	(*AddUpgradeResponse)(nil),    // 7: AddUpgradeResponse
	(*ListUpgradesRequest)(nil),   // 8: ListUpgradesRequest
	(*ListUpgradesResponse)(nil),  // 9: ListUpgradesResponse
	(*CancelUpgradeRequest)(nil),  // 10: CancelUpgradeRequest
	(*CancelUpgradeResponse)(nil), // 11: CancelUpgradeResponse
	(*ForceSyncRequest)(nil),      // 12: ForceSyncRequest
	(*ForceSyncResponse)(nil),     // 13: ForceSyncResponse
	(*timestamppb.Timestamp)(nil), // 14: google.protobuf.Timestamp
}
var file_upgrades_registry_proto_depIdxs = []int32{
	2,  // 0: Upgrade.type:type_name -> UpgradeType
	1,  // 1: Upgrade.status:type_name -> UpgradeStatus
	0,  // 2: Upgrade.step:type_name -> UpgradeStep
	3,  // 3: Upgrade.source:type_name -> ProviderType
	14, // 4: Upgrade.created_at:type_name -> google.protobuf.Timestamp
	4,  // 5: Upgrades.upgrades:type_name -> Upgrade
	4,  // 6: AddUpgradeRequest.upgrade:type_name -> Upgrade
	2,  // 7: ListUpgradesRequest.type:type_name -> UpgradeType
	3,  // 8: ListUpgradesRequest.source:type_name -> ProviderType
	1,  // 9: ListUpgradesRequest.status:type_name -> UpgradeStatus
	4,  // 10: ListUpgradesResponse.upgrades:type_name -> Upgrade
	3,  // 11: CancelUpgradeRequest.source:type_name -> ProviderType
	6,  // 12: UpgradeRegistry.AddUpgrade:input_type -> AddUpgradeRequest
	8,  // 13: UpgradeRegistry.ListUpgrades:input_type -> ListUpgradesRequest
	10, // 14: UpgradeRegistry.CancelUpgrade:input_type -> CancelUpgradeRequest
	12, // 15: UpgradeRegistry.ForceSync:input_type -> ForceSyncRequest
	7,  // 16: UpgradeRegistry.AddUpgrade:output_type -> AddUpgradeResponse
	9,  // 17: UpgradeRegistry.ListUpgrades:output_type -> ListUpgradesResponse
	11, // 18: UpgradeRegistry.CancelUpgrade:output_type -> CancelUpgradeResponse
	13, // 19: UpgradeRegistry.ForceSync:output_type -> ForceSyncResponse
	16, // [16:20] is the sub-list for method output_type
	12, // [12:16] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_upgrades_registry_proto_init() }
func file_upgrades_registry_proto_init() {
	if File_upgrades_registry_proto != nil {
		return
	}
	file_upgrades_registry_proto_msgTypes[0].OneofWrappers = []any{}
	file_upgrades_registry_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_upgrades_registry_proto_rawDesc), len(file_upgrades_registry_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_upgrades_registry_proto_goTypes,
		DependencyIndexes: file_upgrades_registry_proto_depIdxs,
		EnumInfos:         file_upgrades_registry_proto_enumTypes,
		MessageInfos:      file_upgrades_registry_proto_msgTypes,
	}.Build()
	File_upgrades_registry_proto = out.File
	file_upgrades_registry_proto_goTypes = nil
	file_upgrades_registry_proto_depIdxs = nil
}
