// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: blazar.proto

package blazar

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetLatestHeightRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLatestHeightRequest) Reset() {
	*x = GetLatestHeightRequest{}
	mi := &file_blazar_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestHeightRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestHeightRequest) ProtoMessage() {}

func (x *GetLatestHeightRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blazar_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestHeightRequest.ProtoReflect.Descriptor instead.
func (*GetLatestHeightRequest) Descriptor() ([]byte, []int) {
	return file_blazar_proto_rawDescGZIP(), []int{0}
}

type GetLatestHeightResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Height        int64                  `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Network       string                 `protobuf:"bytes,2,opt,name=network,proto3" json:"network,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLatestHeightResponse) Reset() {
	*x = GetLatestHeightResponse{}
	mi := &file_blazar_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestHeightResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestHeightResponse) ProtoMessage() {}

func (x *GetLatestHeightResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blazar_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestHeightResponse.ProtoReflect.Descriptor instead.
func (*GetLatestHeightResponse) Descriptor() ([]byte, []int) {
	return file_blazar_proto_rawDescGZIP(), []int{1}
}

func (x *GetLatestHeightResponse) GetHeight() int64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *GetLatestHeightResponse) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

var File_blazar_proto protoreflect.FileDescriptor

const file_blazar_proto_rawDesc = "" +
	"\n" +
	"\fblazar.proto\"\x18\n" +
	"\x16GetLatestHeightRequest\"K\n" +
	"\x17GetLatestHeightResponse\x12\x16\n" +
	"\x06height\x18\x01 \x01(\x03R\x06height\x12\x18\n" +
	"\anetwork\x18\x02 \x01(\tR\anetwork2Q\n" +
	"\x06Blazar\x12G\n" +
	"\x10GetLastestHeight\x12\x17.GetLatestHeightRequest\x1a\x18.GetLatestHeightResponse\"\x00B\x1bZ\x19internal/pkg/proto/blazarb\x06proto3"

var (
	file_blazar_proto_rawDescOnce sync.Once
	file_blazar_proto_rawDescData []byte
)

func file_blazar_proto_rawDescGZIP() []byte {
	file_blazar_proto_rawDescOnce.Do(func() {
		file_blazar_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_blazar_proto_rawDesc), len(file_blazar_proto_rawDesc)))
	})
	return file_blazar_proto_rawDescData
}

var file_blazar_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_blazar_proto_goTypes = []any{
	(*GetLatestHeightRequest)(nil),  // 0: GetLatestHeightRequest
	(*GetLatestHeightResponse)(nil), // 1: GetLatestHeightResponse
}
var file_blazar_proto_depIdxs = []int32{
	0, // 0: Blazar.GetLastestHeight:input_type -> GetLatestHeightRequest
	1, // 1: Blazar.GetLastestHeight:output_type -> GetLatestHeightResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_blazar_proto_init() }
func file_blazar_proto_init() {
	if File_blazar_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_blazar_proto_rawDesc), len(file_blazar_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_blazar_proto_goTypes,
		DependencyIndexes: file_blazar_proto_depIdxs,
		MessageInfos:      file_blazar_proto_msgTypes,
	}.Build()
	File_blazar_proto = out.File
	file_blazar_proto_goTypes = nil
	file_blazar_proto_depIdxs = nil
}
