// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: blazar.proto

package blazar

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Blazar_GetLastestHeight_FullMethodName = "/Blazar/GetLastestHeight"
)

// BlazarClient is the client API for Blazar service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BlazarClient interface {
	GetLastestHeight(ctx context.Context, in *GetLatestHeightRequest, opts ...grpc.CallOption) (*GetLatestHeightResponse, error)
}

type blazarClient struct {
	cc grpc.ClientConnInterface
}

func NewBlazarClient(cc grpc.ClientConnInterface) BlazarClient {
	return &blazarClient{cc}
}

func (c *blazarClient) GetLastestHeight(ctx context.Context, in *GetLatestHeightRequest, opts ...grpc.CallOption) (*GetLatestHeightResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLatestHeightResponse)
	err := c.cc.Invoke(ctx, Blazar_GetLastestHeight_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BlazarServer is the server API for Blazar service.
// All implementations must embed UnimplementedBlazarServer
// for forward compatibility.
type BlazarServer interface {
	GetLastestHeight(context.Context, *GetLatestHeightRequest) (*GetLatestHeightResponse, error)
	mustEmbedUnimplementedBlazarServer()
}

// UnimplementedBlazarServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBlazarServer struct{}

func (UnimplementedBlazarServer) GetLastestHeight(context.Context, *GetLatestHeightRequest) (*GetLatestHeightResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLastestHeight not implemented")
}
func (UnimplementedBlazarServer) mustEmbedUnimplementedBlazarServer() {}
func (UnimplementedBlazarServer) testEmbeddedByValue()                {}

// UnsafeBlazarServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BlazarServer will
// result in compilation errors.
type UnsafeBlazarServer interface {
	mustEmbedUnimplementedBlazarServer()
}

func RegisterBlazarServer(s grpc.ServiceRegistrar, srv BlazarServer) {
	// If the following call pancis, it indicates UnimplementedBlazarServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Blazar_ServiceDesc, srv)
}

func _Blazar_GetLastestHeight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLatestHeightRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlazarServer).GetLastestHeight(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Blazar_GetLastestHeight_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlazarServer).GetLastestHeight(ctx, req.(*GetLatestHeightRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Blazar_ServiceDesc is the grpc.ServiceDesc for Blazar service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Blazar_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Blazar",
	HandlerType: (*BlazarServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLastestHeight",
			Handler:    _Blazar_GetLastestHeight_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "blazar.proto",
}
