// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: checks.proto

package daemon

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PreCheck int32

const (
	// Try to fetch the docker image before upgrade
	PreCheck_PULL_DOCKER_IMAGE PreCheck = 0
	// Set the node's halt-height before non-governance coordinated upgrades
	PreCheck_SET_HALT_HEIGHT PreCheck = 1
)

// Enum value maps for PreCheck.
var (
	PreCheck_name = map[int32]string{
		0: "PULL_DOCKER_IMAGE",
		1: "SET_HALT_HEIGHT",
	}
	PreCheck_value = map[string]int32{
		"PULL_DOCKER_IMAGE": 0,
		"SET_HALT_HEIGHT":   1,
	}
)

func (x PreCheck) Enum() *PreCheck {
	p := new(PreCheck)
	*p = x
	return p
}

func (x PreCheck) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PreCheck) Descriptor() protoreflect.EnumDescriptor {
	return file_checks_proto_enumTypes[0].Descriptor()
}

func (PreCheck) Type() protoreflect.EnumType {
	return &file_checks_proto_enumTypes[0]
}

func (x PreCheck) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PreCheck.Descriptor instead.
func (PreCheck) EnumDescriptor() ([]byte, []int) {
	return file_checks_proto_rawDescGZIP(), []int{0}
}

type PostCheck int32

const (
	// Check if the gRPC endpoint is reachable
	PostCheck_GRPC_RESPONSIVE PostCheck = 0
	// Check if node reached the next block height
	PostCheck_CHAIN_HEIGHT_INCREASED PostCheck = 1
	// Check if we signed the first block post upgrade
	PostCheck_FIRST_BLOCK_VOTED PostCheck = 2
)

// Enum value maps for PostCheck.
var (
	PostCheck_name = map[int32]string{
		0: "GRPC_RESPONSIVE",
		1: "CHAIN_HEIGHT_INCREASED",
		2: "FIRST_BLOCK_VOTED",
	}
	PostCheck_value = map[string]int32{
		"GRPC_RESPONSIVE":        0,
		"CHAIN_HEIGHT_INCREASED": 1,
		"FIRST_BLOCK_VOTED":      2,
	}
)

func (x PostCheck) Enum() *PostCheck {
	p := new(PostCheck)
	*p = x
	return p
}

func (x PostCheck) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PostCheck) Descriptor() protoreflect.EnumDescriptor {
	return file_checks_proto_enumTypes[1].Descriptor()
}

func (PostCheck) Type() protoreflect.EnumType {
	return &file_checks_proto_enumTypes[1]
}

func (x PostCheck) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PostCheck.Descriptor instead.
func (PostCheck) EnumDescriptor() ([]byte, []int) {
	return file_checks_proto_rawDescGZIP(), []int{1}
}

type CheckStatus int32

const (
	// Check is waiting to be executed
	CheckStatus_PENDING CheckStatus = 0
	// Check is currently being executed
	CheckStatus_RUNNING CheckStatus = 1
	// Check execution has finished
	CheckStatus_FINISHED CheckStatus = 2
)

// Enum value maps for CheckStatus.
var (
	CheckStatus_name = map[int32]string{
		0: "PENDING",
		1: "RUNNING",
		2: "FINISHED",
	}
	CheckStatus_value = map[string]int32{
		"PENDING":  0,
		"RUNNING":  1,
		"FINISHED": 2,
	}
)

func (x CheckStatus) Enum() *CheckStatus {
	p := new(CheckStatus)
	*p = x
	return p
}

func (x CheckStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CheckStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_checks_proto_enumTypes[2].Descriptor()
}

func (CheckStatus) Type() protoreflect.EnumType {
	return &file_checks_proto_enumTypes[2]
}

func (x CheckStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CheckStatus.Descriptor instead.
func (CheckStatus) EnumDescriptor() ([]byte, []int) {
	return file_checks_proto_rawDescGZIP(), []int{2}
}

var File_checks_proto protoreflect.FileDescriptor

const file_checks_proto_rawDesc = "" +
	"\n" +
	"\fchecks.proto*6\n" +
	"\bPreCheck\x12\x15\n" +
	"\x11PULL_DOCKER_IMAGE\x10\x00\x12\x13\n" +
	"\x0fSET_HALT_HEIGHT\x10\x01*S\n" +
	"\tPostCheck\x12\x13\n" +
	"\x0fGRPC_RESPONSIVE\x10\x00\x12\x1a\n" +
	"\x16CHAIN_HEIGHT_INCREASED\x10\x01\x12\x15\n" +
	"\x11FIRST_BLOCK_VOTED\x10\x02*5\n" +
	"\vCheckStatus\x12\v\n" +
	"\aPENDING\x10\x00\x12\v\n" +
	"\aRUNNING\x10\x01\x12\f\n" +
	"\bFINISHED\x10\x02B\x1bZ\x19internal/pkg/proto/daemonb\x06proto3"

var (
	file_checks_proto_rawDescOnce sync.Once
	file_checks_proto_rawDescData []byte
)

func file_checks_proto_rawDescGZIP() []byte {
	file_checks_proto_rawDescOnce.Do(func() {
		file_checks_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_checks_proto_rawDesc), len(file_checks_proto_rawDesc)))
	})
	return file_checks_proto_rawDescData
}

var file_checks_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_checks_proto_goTypes = []any{
	(PreCheck)(0),    // 0: PreCheck
	(PostCheck)(0),   // 1: PostCheck
	(CheckStatus)(0), // 2: CheckStatus
}
var file_checks_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_checks_proto_init() }
func file_checks_proto_init() {
	if File_checks_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_checks_proto_rawDesc), len(file_checks_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_checks_proto_goTypes,
		DependencyIndexes: file_checks_proto_depIdxs,
		EnumInfos:         file_checks_proto_enumTypes,
	}.Build()
	File_checks_proto = out.File
	file_checks_proto_goTypes = nil
	file_checks_proto_depIdxs = nil
}
