// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.2
// source: checks.proto

package daemon

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PreCheck int32

const (
	// Try to fetch the docker image before upgrade
	PreCheck_PULL_DOCKER_IMAGE PreCheck = 0
	// Set the node's halt-height before non-governance coordinated upgrades
	PreCheck_SET_HALT_HEIGHT PreCheck = 1
)

// Enum value maps for PreCheck.
var (
	PreCheck_name = map[int32]string{
		0: "PULL_DOCKER_IMAGE",
		1: "SET_HALT_HEIGHT",
	}
	PreCheck_value = map[string]int32{
		"PULL_DOCKER_IMAGE": 0,
		"SET_HALT_HEIGHT":   1,
	}
)

func (x PreCheck) Enum() *PreCheck {
	p := new(PreCheck)
	*p = x
	return p
}

func (x PreCheck) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PreCheck) Descriptor() protoreflect.EnumDescriptor {
	return file_checks_proto_enumTypes[0].Descriptor()
}

func (PreCheck) Type() protoreflect.EnumType {
	return &file_checks_proto_enumTypes[0]
}

func (x PreCheck) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PreCheck.Descriptor instead.
func (PreCheck) EnumDescriptor() ([]byte, []int) {
	return file_checks_proto_rawDescGZIP(), []int{0}
}

type PostCheck int32

const (
	// Check if the gRPC endpoint is reachable
	PostCheck_GRPC_RESPONSIVE PostCheck = 0
	// Check if node reached the next block height
	PostCheck_CHAIN_HEIGHT_INCREASED PostCheck = 1
	// Check if we signed the first block post upgrade
	PostCheck_FIRST_BLOCK_VOTED PostCheck = 2
)

// Enum value maps for PostCheck.
var (
	PostCheck_name = map[int32]string{
		0: "GRPC_RESPONSIVE",
		1: "CHAIN_HEIGHT_INCREASED",
		2: "FIRST_BLOCK_VOTED",
	}
	PostCheck_value = map[string]int32{
		"GRPC_RESPONSIVE":        0,
		"CHAIN_HEIGHT_INCREASED": 1,
		"FIRST_BLOCK_VOTED":      2,
	}
)

func (x PostCheck) Enum() *PostCheck {
	p := new(PostCheck)
	*p = x
	return p
}

func (x PostCheck) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PostCheck) Descriptor() protoreflect.EnumDescriptor {
	return file_checks_proto_enumTypes[1].Descriptor()
}

func (PostCheck) Type() protoreflect.EnumType {
	return &file_checks_proto_enumTypes[1]
}

func (x PostCheck) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PostCheck.Descriptor instead.
func (PostCheck) EnumDescriptor() ([]byte, []int) {
	return file_checks_proto_rawDescGZIP(), []int{1}
}

type CheckStatus int32

const (
	// Check is waiting to be executed
	CheckStatus_PENDING CheckStatus = 0
	// Check is currently being executed
	CheckStatus_RUNNING CheckStatus = 1
	// Check execution has finished
	CheckStatus_FINISHED CheckStatus = 2
)

// Enum value maps for CheckStatus.
var (
	CheckStatus_name = map[int32]string{
		0: "PENDING",
		1: "RUNNING",
		2: "FINISHED",
	}
	CheckStatus_value = map[string]int32{
		"PENDING":  0,
		"RUNNING":  1,
		"FINISHED": 2,
	}
)

func (x CheckStatus) Enum() *CheckStatus {
	p := new(CheckStatus)
	*p = x
	return p
}

func (x CheckStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CheckStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_checks_proto_enumTypes[2].Descriptor()
}

func (CheckStatus) Type() protoreflect.EnumType {
	return &file_checks_proto_enumTypes[2]
}

func (x CheckStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CheckStatus.Descriptor instead.
func (CheckStatus) EnumDescriptor() ([]byte, []int) {
	return file_checks_proto_rawDescGZIP(), []int{2}
}

var File_checks_proto protoreflect.FileDescriptor

var file_checks_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2a, 0x36,
	0x0a, 0x08, 0x50, 0x72, 0x65, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x12, 0x15, 0x0a, 0x11, 0x50, 0x55,
	0x4c, 0x4c, 0x5f, 0x44, 0x4f, 0x43, 0x4b, 0x45, 0x52, 0x5f, 0x49, 0x4d, 0x41, 0x47, 0x45, 0x10,
	0x00, 0x12, 0x13, 0x0a, 0x0f, 0x53, 0x45, 0x54, 0x5f, 0x48, 0x41, 0x4c, 0x54, 0x5f, 0x48, 0x45,
	0x49, 0x47, 0x48, 0x54, 0x10, 0x01, 0x2a, 0x53, 0x0a, 0x09, 0x50, 0x6f, 0x73, 0x74, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x12, 0x13, 0x0a, 0x0f, 0x47, 0x52, 0x50, 0x43, 0x5f, 0x52, 0x45, 0x53, 0x50,
	0x4f, 0x4e, 0x53, 0x49, 0x56, 0x45, 0x10, 0x00, 0x12, 0x1a, 0x0a, 0x16, 0x43, 0x48, 0x41, 0x49,
	0x4e, 0x5f, 0x48, 0x45, 0x49, 0x47, 0x48, 0x54, 0x5f, 0x49, 0x4e, 0x43, 0x52, 0x45, 0x41, 0x53,
	0x45, 0x44, 0x10, 0x01, 0x12, 0x15, 0x0a, 0x11, 0x46, 0x49, 0x52, 0x53, 0x54, 0x5f, 0x42, 0x4c,
	0x4f, 0x43, 0x4b, 0x5f, 0x56, 0x4f, 0x54, 0x45, 0x44, 0x10, 0x02, 0x2a, 0x35, 0x0a, 0x0b, 0x43,
	0x68, 0x65, 0x63, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x50, 0x45,
	0x4e, 0x44, 0x49, 0x4e, 0x47, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x52, 0x55, 0x4e, 0x4e, 0x49,
	0x4e, 0x47, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x46, 0x49, 0x4e, 0x49, 0x53, 0x48, 0x45, 0x44,
	0x10, 0x02, 0x42, 0x1b, 0x5a, 0x19, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70,
	0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_checks_proto_rawDescOnce sync.Once
	file_checks_proto_rawDescData = file_checks_proto_rawDesc
)

func file_checks_proto_rawDescGZIP() []byte {
	file_checks_proto_rawDescOnce.Do(func() {
		file_checks_proto_rawDescData = protoimpl.X.CompressGZIP(file_checks_proto_rawDescData)
	})
	return file_checks_proto_rawDescData
}

var file_checks_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_checks_proto_goTypes = []any{
	(PreCheck)(0),    // 0: PreCheck
	(PostCheck)(0),   // 1: PostCheck
	(CheckStatus)(0), // 2: CheckStatus
}
var file_checks_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_checks_proto_init() }
func file_checks_proto_init() {
	if File_checks_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_checks_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_checks_proto_goTypes,
		DependencyIndexes: file_checks_proto_depIdxs,
		EnumInfos:         file_checks_proto_enumTypes,
	}.Build()
	File_checks_proto = out.File
	file_checks_proto_rawDesc = nil
	file_checks_proto_goTypes = nil
	file_checks_proto_depIdxs = nil
}
